from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
for path in (ROOT, BACKEND):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from app.services.review_service import ReviewService


def generate_review_tasks() -> dict[str, int]:
    """Persist actionable review items generated by ReviewService.

    The generator is intentionally low-friction: it stores only meaningful review
    items, deduplicates by stable keys, and does not create tasks for healthy
    empty-state signals such as NO_MAJOR_RISK.
    """
    result = ReviewService().sync_tasks_from_overview()
    return {"count": int(result.get("count") or 0), "inserted": int(result.get("inserted") or 0)}


if __name__ == "__main__":
    print(generate_review_tasks())
