CREATE TABLE IF NOT EXISTS financial_statement_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_date TEXT NOT NULL,
    period_type TEXT NOT NULL DEFAULT 'ANNUAL',
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    revenue REAL,
    net_profit REAL,
    operating_cash_flow REAL,
    total_assets REAL,
    total_liabilities REAL,
    equity REAL,
    gross_margin REAL,
    net_margin REAL,
    debt_ratio REAL,
    source TEXT,
    source_mode TEXT NOT NULL DEFAULT 'SAMPLE',
    data_date TEXT NOT NULL,
    data_version TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(report_date, period_type, symbol)
);

CREATE TABLE IF NOT EXISTS financial_metric_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric_date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    revenue_growth REAL,
    net_profit_growth REAL,
    roe REAL,
    roa REAL,
    operating_cash_flow_ratio REAL,
    gross_margin REAL,
    net_margin REAL,
    debt_ratio REAL,
    quality_score REAL,
    growth_score REAL,
    cashflow_score REAL,
    balance_score REAL,
    source TEXT,
    source_mode TEXT NOT NULL DEFAULT 'SAMPLE',
    data_date TEXT NOT NULL,
    data_version TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(metric_date, symbol)
);

CREATE TABLE IF NOT EXISTS valuation_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    valuation_date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    pe_ttm REAL,
    pb REAL,
    ps REAL,
    dividend_yield REAL,
    pe_percentile REAL,
    pb_percentile REAL,
    valuation_score REAL,
    valuation_state TEXT,
    source TEXT,
    source_mode TEXT NOT NULL DEFAULT 'SAMPLE',
    data_date TEXT NOT NULL,
    data_version TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(valuation_date, symbol)
);

CREATE TABLE IF NOT EXISTS stock_quality_snapshot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quality_date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    total_score REAL NOT NULL,
    quality_state TEXT NOT NULL,
    growth_score REAL,
    profitability_score REAL,
    cashflow_score REAL,
    balance_score REAL,
    valuation_score REAL,
    conclusion TEXT,
    risk_note TEXT,
    source TEXT,
    source_mode TEXT NOT NULL DEFAULT 'SAMPLE',
    data_date TEXT NOT NULL,
    data_version TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(quality_date, symbol)
);
